baseURL: https://pfteststorage.z33.web.core.windows.net/client
title: Client Docs
theme: book

# Book configuration
disablePathToLower: true
enableGitInfo: false
disableKinds: ['taxonomy', 'taxonomyTerm']
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1

contentDir: ../client/content
staticDir: ../client/images

defaultContentLanguage: en-us
defaultContentLanguageInSubdir: true
enableMissingTranslationPlaceholders: true


languages:
  en-us:
    languageName: English (US)
    weight: 1
  en-gb:
    languageName: English (GB)
    weight: 2

params:
# 'dimensions' for Dimensions, 'voice' for Dimensions Voice
  BookTheme: voice
# comment out for Dimensions
  BookLogo: favicon-voice.png

  BookToC: true
  BookSection: /
  BookDateFormat: "Jan 2, 2006"
  BookSearch: true
  BookComments: false
 
  

